import { z } from 'zod';
import { accountIdSchema,intentIdSchema,proposalIdSchema,decisionIdSchema,entryIdSchema,entryPositionSchema,headPositionSchema,idempotencyKeySchema,requestIdSchema,operationKindSchema,instantSchema,asOfSchema,scopeHashSchema,sourceSchema } from '../ids.ts';
import { freshnessSchema,durationSchema } from '../time.ts';
import { operationEnvelopeSchema, serializableSchema } from '../provider/indexed.ts';
import type { Serializable } from '../provider/indexed.ts';
import { reasonTreeSchema,decisionScopeSchema,ledgerEntrySchema,unknownLedgerEntrySchema } from '../ledger/entries.ts';
import { decisionActionSchema,decisionResponseSchema } from '../issues.ts';
import { readinessResponseSchema } from '../readiness.ts';
export { readinessResponseSchema,processSnapshotSchema } from '../readiness.ts';
export type { ReadinessResponse,ProcessSnapshot } from '../readiness.ts';
// Zod represents an omitted optional property as T | undefined; only that omission is allowed.
type JsonOutput<T> = T extends Serializable ? T : T extends (...args:never[])=>unknown ? never : T extends readonly unknown[] ? {[K in keyof T]:JsonOutput<T[K]>} : T extends object ? {[K in keyof T]:JsonOutput<Exclude<T[K],undefined>> | (Pick<T,K> extends Required<Pick<T,K>> ? never : undefined)} : never;
export function readProjectionResponseSchema<T extends z.ZodType>(valueSchema:T & (z.output<T> extends JsonOutput<z.output<T>> ? unknown : never)){const serializableValue=valueSchema.refine(value=>serializableSchema.safeParse(value).success,'Projection value must be Serializable');return z.strictObject({source:sourceSchema,asOf:asOfSchema,freshness:freshnessSchema,value:serializableValue}).superRefine((value,context)=>{if(value.freshness.kind!=='missing'&&value.freshness.asOf!==value.asOf)context.addIssue({code:'custom',message:'Projection freshness time mismatch'});});}
export type ReadProjectionResponse<T> = T extends JsonOutput<T> ? {readonly source:z.output<typeof sourceSchema>;readonly asOf:z.output<typeof asOfSchema>;readonly freshness:z.output<typeof freshnessSchema>;readonly value:T} : never;
export const intentProposalRequestSchema=z.strictObject({requestId:requestIdSchema,intentId:intentIdSchema,idempotencyKey:idempotencyKeySchema,proposalId:proposalIdSchema.optional(),accountId:accountIdSchema,operationKind:operationKindSchema,operation:operationEnvelopeSchema,why:reasonTreeSchema,expiresAt:instantSchema}).superRefine((value,context)=>{if(value.operationKind!==value.operation.kind)context.addIssue({code:'custom',message:'Operation kind mismatch'});});
export type IntentProposalRequest=z.output<typeof intentProposalRequestSchema>;
export const intentProposalResponseSchema=z.strictObject({intentId:intentIdSchema,entryId:entryIdSchema,position:entryPositionSchema,status:z.literal('proposed')});
export type IntentProposalResponse=z.output<typeof intentProposalResponseSchema>;
export const authorizationDecisionRequestSchema=z.strictObject({decisionId:decisionIdSchema,action:decisionActionSchema,scope:decisionScopeSchema,scopeHash:scopeHashSchema});
export type AuthorizationDecisionRequest=z.output<typeof authorizationDecisionRequestSchema>;
export const authorizationDecisionResponseSchema=decisionResponseSchema;
export type AuthorizationDecisionResponse=z.output<typeof authorizationDecisionResponseSchema>;
export const intentOutcomeSchema=z.enum(['proposed','authorized','withdrawn','rejected','expired','attempting','accepted','rejectedByProvider','unknown','awaitingReview','filled','partiallyFilled','cancelled','abandoned']);
export const intentDetailResponseSchema=z.strictObject({intentId:intentIdSchema,position:entryPositionSchema,outcome:intentOutcomeSchema,operation:operationEnvelopeSchema});
export type IntentDetailResponse=z.output<typeof intentDetailResponseSchema>;
export const intentListResponseSchema=z.strictObject({intents:z.array(intentDetailResponseSchema)});
export type IntentListResponse=z.output<typeof intentListResponseSchema>;
export const commandResponseSchema=z.discriminatedUnion('kind',[z.strictObject({kind:z.literal('recorded'),requestId:requestIdSchema,position:entryPositionSchema}),z.strictObject({kind:z.literal('completed'),requestId:requestIdSchema})]);
export type CommandResponse=z.output<typeof commandResponseSchema>;
export const proposalCreateRequestSchema=z.strictObject({intentIds:z.tuple([intentIdSchema],intentIdSchema),proposalId:proposalIdSchema,why:reasonTreeSchema});
export type ProposalCreateRequest=z.output<typeof proposalCreateRequestSchema>;
export const proposalCreateResponseSchema=z.strictObject({proposalId:proposalIdSchema,intentIds:z.tuple([intentIdSchema],intentIdSchema),position:entryPositionSchema});
export type ProposalCreateResponse=z.output<typeof proposalCreateResponseSchema>;
export const oneShotIntentRequestSchema=z.strictObject({intent:intentProposalRequestSchema,decision:authorizationDecisionRequestSchema});
export type OneShotIntentRequest=z.output<typeof oneShotIntentRequestSchema>;
export const ledgerEntryWireSchema=ledgerEntrySchema;
export type LedgerEntryWire=z.output<typeof ledgerEntryWireSchema>;
export const unknownLedgerEntryWireSchema=unknownLedgerEntrySchema;
export type UnknownLedgerEntryWire=z.output<typeof unknownLedgerEntryWireSchema>;
export const ledgerEntriesQuerySchema=z.strictObject({fromPosition:headPositionSchema.optional(),limit:z.number().int().min(1).max(2000).default(500)});
export type LedgerEntriesQuery=z.output<typeof ledgerEntriesQuerySchema>;
export const ledgerEntriesResponseSchema=z.strictObject({entries:z.array(z.union([ledgerEntryWireSchema,unknownLedgerEntryWireSchema])),nextPosition:headPositionSchema});
export type LedgerEntriesResponse=z.output<typeof ledgerEntriesResponseSchema>;
export const cursorMapSchema=z.record(accountIdSchema,headPositionSchema);
export type CursorMap=z.output<typeof cursorMapSchema>;
export const eventsQuerySchema=z.strictObject({cursors:cursorMapSchema.optional(),wait:z.union([z.literal(0),durationSchema.refine(value=>value<=25000,'Long poll exceeds 25000 milliseconds')]).default(0),limit:z.number().int().min(1).max(2000).default(500)});
export type EventsQuery=z.output<typeof eventsQuerySchema>;
export const eventItemSchema=z.strictObject({source:sourceSchema,accountId:accountIdSchema,position:entryPositionSchema,entry:z.union([ledgerEntryWireSchema,unknownLedgerEntryWireSchema])}).superRefine((item,context)=>{if(item.source!==item.entry.source||item.accountId!==item.entry.accountId||item.position!==item.entry.position)context.addIssue({code:'custom',message:'Fan-in tag mismatches ledger entry'});});
export type EventItem=z.output<typeof eventItemSchema>;
export const eventsResponseSchema=z.strictObject({items:z.array(eventItemSchema),nextCursors:cursorMapSchema,readiness:readinessResponseSchema});
export type EventsResponse=z.output<typeof eventsResponseSchema>;
export const errorCodeSchema=z.enum(['Unauthorized','LegacyRouteRemoved','InvalidRequest','AccountNotFound','ScopeMismatch','CapabilityUnsupported','ServiceDraining','IntentExpired','IdempotencyConflict','DecisionConflict','ReversalTargetAlreadyExecuted','ProviderRejected','ProviderUnknown','ProviderTransportFailure','ProviderParseFailure','ReadinessUnavailable','CursorInvalid','Timeout','InternalError']);
export type ErrorCode=z.output<typeof errorCodeSchema>;
const errorBase={message:z.string().min(1),requestId:requestIdSchema,why:reasonTreeSchema};
export const errorEnvelopeSchema=z.union([z.strictObject({...errorBase,code:z.literal('LegacyRouteRemoved'),replacement:z.string().min(1)}),z.strictObject({...errorBase,code:z.literal('Timeout'),phase:z.enum(['ingress','providerRead','drain'])}),z.strictObject({...errorBase,code:errorCodeSchema.exclude(['LegacyRouteRemoved','Timeout'])})]);
export type ErrorEnvelope=z.output<typeof errorEnvelopeSchema>;
